{
 "title": "分布式缓存服务(DCS)",
 "description": "【华为云DCS支持的监控指标】https://support.flexibleengine.com/usermanual-dcs/dcs-ug-0713011.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "flexibleengine_epinfo" } },
   {
    "name": "cache_mode",
    "label": "缓存类型",
    "query": {
     "query": "label_values(flexibleengine_sys_dcs_cpu_usage{epId=~\"$EPS\"},cache_mode)"
    }
   },
   {
    "name": "hostIP",
    "label": "主机IP",
    "query": {
     "query": "label_values(flexibleengine_sys_dcs_cpu_usage{epId=~\"$EPS\",cache_mode=~\"$cache_mode\"},ip)"
    }
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(flexibleengine_sys_dcs_cpu_usage{epId=~\"$EPS\",cache_mode=~\"$cache_mode\",ip=~\"$hostIP\"},name)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(flexibleengine_sys_dcs_cpu_usage{epId=~\"$EPS\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览（企业项目）企业项目：$EPS，当前选中主机：$hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "EPS"
  },
  {
   "title": "服务器资源总览表【企业项目：$EPS，主机总数：$total】",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_cpu_usage{epId=~\"$EPS\"} -0",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "avg(flexibleengine_sys_dcs_memory_usage{epId=~\"$EPS\"}) by (private_ip)",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "avg(flexibleengine_sys_dcs_keyspace_hits_perc{epId=~\"$EPS\"}) by (private_ip)",
     "legendFormat": "缓存命中率"
    },
    {
     "expr": "avg(flexibleengine_sys_dcs_connected_clients{epId=~\"$EPS\"}) by (private_ip)",
     "legendFormat": "活跃的客户端数量"
    },
    {
     "expr": "avg(flexibleengine_sys_dcs_total_connections_received{epId=~\"$EPS\"}) by (private_ip)",
     "legendFormat": "新建连接数"
    },
    {
     "expr": "avg(flexibleengine_sys_dcs_command_max_delay{epId=~\"$EPS\"}) by (private_ip)",
     "legendFormat": "命令最大时延"
    },
    {
     "expr": "avg(flexibleengine_sys_dcs_rx_controlled{epId=~\"$EPS\"}) by (private_ip)",
     "legendFormat": "流控次数"
    }
   ]
  },
  { "title": "资源明细：【$EPS】【$hostIP】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "EPS" },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_cpu_usage{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_memory_usage{ip=~\"$hostIP\"} - 0",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-内存使用率"
    }
   ]
  },
  {
   "title": "缓存键总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_keys{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-缓存建总数"
    }
   ]
  },
  {
   "title": "缓存过期键总数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_expires{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-有过期时间的键总数"
    },
    {
     "expr": "0 - flexibleengine_sys_dcs_expired_keys{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-已过期的键总数"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_keyspace_hits_perc{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-缓存命中率"
    }
   ]
  },
  {
   "title": "每秒并发操作数",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_instantaneous_ops{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-每秒并发操作数"
    }
   ]
  },
  {
   "title": "带宽使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_bandwidth_usage{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-带宽使用率"
    }
   ]
  },
  {
   "title": "网络瞬时（输入/输出）流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "Kbits", "label": "输出（-）/输入（+）" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_instantaneous_input_kbps{ip=~'$hostIP'} - 0",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-网络瞬时输入流量"
    },
    {
     "expr": "0 - flexibleengine_sys_dcs_instantaneous_output_kbps{ip=~'$hostIP'}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-网络瞬时输出流量"
    }
   ]
  },
  {
   "title": "是否存在慢日志",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bool" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_is_slow_log_exist{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-是否存在慢日志"
    }
   ]
  },
  {
   "title": "流控次数",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_rx_controlled{ip=~'$hostIP'}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-流控次数"
    }
   ]
  },
  {
   "title": "命令最大时延",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_dcs_command_max_delay{ip=~\"$hostIP\"}",
     "legendFormat": "【{{ip}}_{{name}}_{{group_name}}_{{node_type}}_{{private_ip}}】-命令最大时延"
    }
   ]
  }
 ]
}