{
 "title": "弹性云服务器(ECS)",
 "description": "【ECS Supported Metrics】https://docs.prod-cloud-ocb.orange-business.com/usermanual/ecs/en-us_topic_0030911465.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "flexibleengine_epinfo" } },
   {
    "name": "hostIP",
    "label": "主机IP",
    "query": {
     "query": "label_values(flexibleengine_agt_ecs_cpu_usage{epId=~\"$EPS\"},hostIP)"
    }
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(flexibleengine_agt_ecs_cpu_usage{epId=~\"$EPS\",hostIP=~\"$hostIP\"},hostname)"
    }
   },
   {
    "name": "total",
    "query": {
     "query": "query_result(count(flexibleengine_agt_ecs_net_tcp_established{epId=~\"$EPS\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览（企业项目）企业项目：$EPS，当前选中主机：$hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "EPS"
  },
  {
   "title": "服务器资源总览表【企业项目：$EPS，主机总数：$total】",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\n连接数：CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数。",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_cpu_usage{epId=~\"$EPS\"} -0",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "flexibleengine_agt_ecs_mem_usedPercent{epId=~\"$EPS\"} -0",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "flexibleengine_agt_ecs_SlAsH_disk_usedPercent{epId=~\"$EPS\"} - 0",
     "legendFormat": "磁盘使用率"
    },
    {
     "expr": "flexibleengine_agt_ecs_net_tcp_total{epId=~'$EPS'} ",
     "legendFormat": "连接数"
    },
    {
     "expr": "avg(flexibleengine_agt_ecs_net_bitSent{epId=~'$EPS'}) by (hostIP)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "avg(flexibleengine_agt_ecs_net_bitRecv{epId=~'$EPS'}) by (hostIP)",
     "legendFormat": "上传带宽"
    },
    {
     "expr": "avg(flexibleengine_agt_ecs_load_average5{epId=~\"$EPS\"}) by (hostIP)",
     "legendFormat": "5分钟负载"
    }
   ]
  },
  {
   "title": "$EPS：整体总负载与整体平均CPU使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "总负载" }
   ],
   "targets": [
    {
     "expr": "avg(flexibleengine_agt_ecs_load_average5{epId=~\"$EPS\"}) * 100",
     "legendFormat": "总5分钟负载"
    },
    {
     "expr": "avg((flexibleengine_agt_ecs_cpu_usage{epId=~\"$EPS\"}))",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "$EPS：整体平均内存使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "内存使用率" }
   ],
   "targets": [
    {
     "expr": "avg(flexibleengine_agt_ecs_mem_usedPercent{epId=~\"$EPS\"})",
     "legendFormat": "总平均使用率"
    }
   ]
  },
  {
   "title": "$EPS：整体平均磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "percent", "label": "磁盘使用率" }
   ],
   "targets": [
    {
     "expr": "avg(flexibleengine_agt_ecs_disk_usedPercent + on (instance_id) group_left (epId,hostIP,hostname) flexibleengine_sys_ecs_cpu_util*0)",
     "legendFormat": "系统磁盘总使用率"
    }
   ]
  },
  { "title": "资源明细：【$EPS】【$hostIP】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "EPS" },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_cpu_usage{hostIP=~\"$hostIP\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-CPU使用率"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_mem_usedPercent{hostIP=~\"$hostIP\"}",
     "legendFormat": "{{hostIP}}({{hostname}})内存使用率"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_load_average5{hostIP=~\"$hostIP\"}",
     "legendFormat": "{{hostIP}}({{hostname}})-5分钟负载"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_disk_usedPercent + on (instance_id) group_left (EPS,hostIP,hostname) flexibleengine_sys_ecs_cpu_util{epId=~\"$EPS\",hostIP=~\"$hostIP\"}*0",
     "legendFormat": "{{hostIP}}_{{hostname}}_{{mount_point}}-磁盘使用率"
    }
   ]
  },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Read Requests: 每个磁盘分区每秒读完成次数\n\nWrite Requests: 每个磁盘分区每秒写完成次数",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_ecs_disk_read_requests_rate{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘读IOPS"
    },
    {
     "expr": "flexibleengine_sys_ecs_disk_write_requests_rate{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘写IOPS"
    }
   ]
  },
  {
   "title": "磁盘I/O使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_disk_ioUtils + on (instance_id) group_left (epId,hostIP,hostname) flexibleengine_sys_ecs_cpu_util{epId=~\"$EPS\",hostIP=~\"$hostIP\"}*0 ",
     "legendFormat": " {{hostIP}}_{{hostname}}_{{disk}}-磁盘I/O使用率"
    }
   ]
  },
  {
   "title": "磁盘读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_ecs_disk_read_bytes_rate{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘读操作速率"
    },
    {
     "expr": "flexibleengine_sys_ecs_disk_write_bytes_rate{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-磁盘写操作速率"
    }
   ]
  },
  {
   "title": "磁盘iNode使用率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_disk_inodesUsedPercent + on (instance_id) group_left (epId,hostIP,hostname) flexibleengine_sys_ecs_cpu_util{epId=~\"$EPS\",hostIP=~\"$hostIP\"}*0 ",
     "legendFormat": "{{hostIP}}_{{hostname}}_{{mount_point}}-磁盘iNode使用率(/)"
    }
   ]
  },
  {
   "title": "网络带宽使用",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bps", "label": "出网（-）/入网（+）" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_net_bitRecv{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-入网带宽"
    },
    {
     "expr": "flexibleengine_agt_ecs_net_bitSent{hostIP=~'$hostIP'} * -1",
     "legendFormat": "{{hostIP}}({{hostname}})-出网带宽"
    }
   ]
  },
  {
   "title": "网络连接信息",
   "type": "graph",
   "description": "net_tcp_total - 统计测量对象网卡所有状态的TCP连接数总和\n\nnet_tcp_established - 统计测量对象网卡处于ESTABLISHED状态的TCP连接数量\n",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_agt_ecs_net_tcp_total{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-TCP连接数总和"
    },
    {
     "expr": "flexibleengine_agt_ecs_net_tcp_established{hostIP=~'$hostIP'}",
     "legendFormat": "{{hostIP}}({{hostname}})-ESTABLISHED状态的TCP连接数量"
    }
   ]
  }
 ]
}