{
 "title": "弹性公网IP和带宽(VPC)",
 "description": "【华为云VPC监控指标说明】https://support.flexibleengine.com/intl/zh-cn/usermanual-vpc/vpc010012.html",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "EPS", "label": "企业项目", "query": { "query": "flexibleengine_epinfo" } }
  ]
 },
 "panels": [
  { "title": "带宽 资源总览（企业项目）企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "带宽资源总览表【企业项目：$EPS】",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(flexibleengine_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\"}) by (name,bandwidth_id)",
     "legendFormat": "入网带宽"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\"}) by (name,bandwidth_id)",
     "legendFormat": "入网使用率"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress=~\"\"}) by (name,bandwidth_id)",
     "legendFormat": "入网流量"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\"}) by (name,bandwidth_id)",
     "legendFormat": "出网带宽"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\"}) by (name,bandwidth_id)",
     "legendFormat": "出网带宽使用率"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress=~\"\"}) by (name,bandwidth_id)",
     "legendFormat": "出网流量"
    }
   ]
  },
  { "title": "带宽 资源详情（企业项目）企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "EPS" },
  {
   "title": "入网带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "入网带宽使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "入网流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress=~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "出网带宽",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress=~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "出网带宽使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress=~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "出网流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress=~\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "弹性公网IP 资源总览（企业项目）企业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }, "repeat": "EPS" },
  {
   "title": "弹性公网IP资源总览表【企业项目：$EPS】",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg(flexibleengine_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\"}) by (name,publicip_id)",
     "legendFormat": "入网带宽"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\"}) by (name,publicip_id)",
     "legendFormat": "入网使用率"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress!=\"\"}) by (name,publicip_id)",
     "legendFormat": "入网流量"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\"}) by (name,publicip_id)",
     "legendFormat": "出网带宽"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\"}) by (name,publicip_id)",
     "legendFormat": "出网带宽使用率"
    },
    {
     "expr": "avg(flexibleengine_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress!=\"\"}) by (name,publicip_id)",
     "legendFormat": "出网流量"
    }
   ]
  },
  { "title": "弹性公网IP 详情 业项目：$EPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }, "repeat": "EPS" },
  {
   "title": "入网带宽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_downstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "入网带宽使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_downstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "入网流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_down_stream{epId=~\"$EPS\",publicIpAddress!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "出网带宽",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_upstream_bandwidth{epId=~\"$EPS\",publicIpAddress!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "出网带宽使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_upstream_bandwidth_usage{epId=~\"$EPS\",publicIpAddress!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "出网流量",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_vpc_up_stream{epId=~\"$EPS\",publicIpAddress!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}