{
 "title": "Web application firewall(WAF)",
 "description": "【WAF Supported Metrics】https://docs.prod-cloud-ocb.orange-business.com/usermanual/waf/waf_01_0092.html",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "waf_name",
    "label": "protect domain name",
    "query": {
     "query": "label_values(flexibleengine_sys_waf_requests{},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource details：【$waf_name】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "EPS" },
  {
   "title": "Request volume",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_requests{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-Request_volume"
    }
   ]
  },
  {
   "title": "Total_incoming_network_traffic/total_outgoing_network_traffic(5min）",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    {
     "format": "mbytes",
     "label": "Total_inbound_traffic（+）/Total_outbound_traffic（-）"
    }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_inbound_traffic{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-Total_inbound_traffic(5min)"
    },
    {
     "expr": "0 - flexibleengine_sys_waf_outbound_traffic{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-Total_outbound_traffic(5min)"
    }
   ]
  },
  {
   "title": "Incoming network traffic/outgoing network traffic (average value + peak value)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    {
     "format": "Mibits",
     "label": "Inbound traffic (+)/Outbound traffic (-)"
    }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_inbound_traffic_peak{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-The_peak_value_of_inbound_traffic(5min)"
    },
    {
     "expr": "0 - flexibleengine_sys_waf_outbound_traffic_peak{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-Peak_value_of_outbound_traffic(5min)"
    },
    {
     "expr": "flexibleengine_sys_waf_inbound_traffic_mean{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-Average_value_of_incoming_network_traffic(5min)"
    },
    {
     "expr": "0 - flexibleengine_sys_waf_outbound_traffic_mean{waf_instance_id=~\"$waf_instance_id\"}",
     "legendFormat": "{{name}}-Average_outbound_traffic(5min)"
    }
   ]
  },
  {
   "title": "WAF_return_code 2XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_waf_http_2xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF_return_code（2XX）"
    }
   ]
  },
  {
   "title": "WAF_return_code3XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_waf_http_3xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF_return_code（3XX）"
    }
   ]
  },
  {
   "title": "WAF_return_code4XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_waf_http_4xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF_return_code（4XX）"
    }
   ]
  },
  {
   "title": "WAF_return_code5XX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_waf_http_5xx{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-WAF_return_code（5XX）"
    }
   ]
  },
  {
   "title": "QPS_peak",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_qps_peak{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-QPS_peak"
    }
   ]
  },
  {
   "title": "QPS mean",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "flexibleengine_sys_waf_qps_mean{name=~\"$waf_name\"}",
     "legendFormat": "{{name}}-QPS_mean"
    }
   ]
  }
 ]
}